RED := $(shell tput setaf 1)
RESET := $(shell tput sgr0)

default:
	@printf "$(RED)Part 2 will take up to 30 seconds to run. While the answer for part 1 will be exact, your answer for part 2 might be off by 1 or 2 depending on your specific input.$(RESET)\n"
	@python3 main.py
	@python3 main1.py